services:
  oracle:
    image: container-registry.oracle.com/database/free:23.26.1.0
    container_name: ${CONTAINER_DB_NAME}
    restart: unless-stopped
    env_file: 
      - .env

    ports:
      - "${PORT_DB}:1521"

    volumes:
      - oracle_dados_wsl:/opt/oracle/oradata
    
    networks:
      - computer_vision_network

    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  fastapi_app:
    build: 
      context: ./src/api
      dockerfile: ./src/api/Dockerfile
    container_name: ${CONTAINER_API}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT_APi}:8000"
    volumes:
      - ./src/api:/app
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - computer_vision_network