services:
  oracle:
    image: container-registry.oracle.com/database/free:23.26.1.0
    container_name: ${CONTAINER_DB_NAME}
    restart: unless-stopped
    env_file: 
      - .env

    ports:
      - "${PORT_DB}:1521"

    volumes:
      - oracle_dados_wsl:/opt/oracle/oradata

    shm_size: "1g" 
    
    networks:
      - computer_vision_network

    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  fastapi_app:
    build: 
      context: ./src/api
      dockerfile: Dockerfile
    container_name: ${CONTAINER_API}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT_API}:8000"
    volumes:
      - ./src/api:/app
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - computer_vision_network

  streamlit:
    build:
      context: ./src/dashboard
      dockerfile: Dockerfile
    container_name: ${CONTAINER_STREAMLIT}
    restart: unless-stopped
    env_file:
      - .env
    ports: 
      - "${PORT_STREAMLIT}:8501"
    volumes: 
      - ./src/dashboard:/app
    depends_on:
      fastapi_app:
        condition: service_healthy

    networks:
      - computer_vision_network

networks:
  computer_vision_network:
    driver: bridge

volumes:
  oracle_dados_wsl: